# Generated by Django 2.2 on 2021-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211204_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/icon-profile.jpg', upload_to='profile_pictures', verbose_name='Profile Picture'),
        ),
    ]
