# Generated by Django 2.2 on 2021-12-05 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postrecipe',
            old_name='cookTime',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='postrecipe',
            old_name='prepTime',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='postrecipe',
            old_name='recipeImage',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='postrecipe',
            old_name='totalTime',
            new_name='total_time',
        ),
        migrations.RemoveField(
            model_name='postrecipe',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postrecipe',
            name='recipe_yield',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postrecipe',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Post'),
            preserve_default=False,
        ),
    ]
