# Generated by Django 2.2 on 2021-12-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211204_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
